# Site settings
title: Yongha Hwang 
email: ahgnoy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Architectural data scientist
baseurl:  # the subpath of your site, e.g. /blog/
url:  yonghah.github.io
twitter_username: pathoverlap 
github_username: yonghah 

# Build settings
markdown: kramdown

highlighter: rouge 

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"
gems: [jekyll-paginate]

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

